service: lambda-closure

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  closure:
    handler: closure.handler
    events:
      - http: GET /

plugins:
  - serverless-offline
